SkillsFundingAgency/das-commitments

src/Build.fsx
Changed EmployerApprenticeshipService to Commitments
=> Fixed fake script

src/SFA.DAS.Commitments.Api.Types/Apprenticeship.cs, src/SFA.DAS.Commitments.Api.UnitTests/Controllers/EmployerControllerTests/WhenUpdatingAnApprenticeship.cs, src/SFA.DAS.Commitments.Api.UnitTests/Controllers/ProviderControllerTests/WhenCreatingAnApprenticeship.cs, src/SFA.DAS.Commitments.Api.UnitTests/Controllers/ProviderControllerTests/WhenUpdatingAnApprenticeship.cs, src/SFA.DAS.Commitments.Api.UnitTests/SFA.DAS.Commitments.Api.UnitTests.csproj, src/SFA.DAS.Commitments.Api/Controllers/EmployerController.cs, src/SFA.DAS.Commitments.Api/Controllers/ProviderController.cs, src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenCreatingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenValidatingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenValidatingCommand.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateCommitment/WhenCreatingCommitment.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeship/WhenUpdatingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeship/WhenValidatingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeship/WhenValidatingCommand.cs, src/SFA.DAS.Commitments.Application.UnitTests/SFA.DAS.Commitments.Application.UnitTests.csproj, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeship/CreateApprenticeshipCommand.cs, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeship/CreateApprenticeshipValidator.cs, src/SFA.DAS.Commitments.Application/Commands/CreateCommitment/CreateCommitmentCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeship/UpdateApprenticeshipCommand.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeship/UpdateApprenticeshipCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeship/UpdateApprenticeshipValidator.cs, src/SFA.DAS.Commitments.Application/Queries/GetApprenticeship/GetApprenticeshipQueryHandler.cs, src/SFA.DAS.Commitments.Application/Queries/GetCommitment/GetCommitmentQueryHandler.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj, src/SFA.DAS.Commitments.Domain/Data/ICommitmentRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Data/CommitmentRepository.cs
There feels like quite a bit of duplication at the moment.
=> Create/Update apprenticeship for provider & employer

src/SFA.DAS.Commitments.Api.Client/CommitmentsApi.cs, src/SFA.DAS.Commitments.Api.Client/ICommitmentsApi.cs, src/SFA.DAS.Commitments.Api.UnitTests/Controllers/EmployerControllerTests/WhenUpdatingCommitmentStatus.cs, src/SFA.DAS.Commitments.Api.UnitTests/SFA.DAS.Commitments.Api.UnitTests.csproj, src/SFA.DAS.Commitments.Api/Controllers/EmployerController.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateCommitmentStatus/WhenUpdatingCommitmentStatus.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateCommitmentStatus/WhenValidatingCommand.cs, src/SFA.DAS.Commitments.Application.UnitTests/SFA.DAS.Commitments.Application.UnitTests.csproj, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentStatus/UpdateCommitmentStatusCommand.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentStatus/UpdateCommitmentStatusCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentStatus/UpdateCommitmentStatusValidator.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj, src/SFA.DAS.Commitments.Domain/Data/ICommitmentRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Data/CommitmentRepository.cs
New Api method for employer and update to the api client. (Will copy client and create pull request in employer repo)
=> Added API patch for commitment - currently only updating the status.

src/SFA.DAS.Commitments.Api/Web.config, src/SFA.DAS.Commitments.Application.UnitTests/ApprenticeshipTestDataHelper.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenCreatingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenValidatingCommand.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateCommitment/WhenCreatingCommitment.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateCommitment/WhenValidatingApprenticeships.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateCommitment/WhenValidatingCommitment.cs, src/SFA.DAS.Commitments.Application.UnitTests/SFA.DAS.Commitments.Application.UnitTests.csproj, src/SFA.DAS.Commitments.Application/Commands/ApprenticeshipValidator.cs, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeship/CreateApprenticeshipValidator.cs, src/SFA.DAS.Commitments.Application/Commands/CreateCommitment/CreateCommitmentValidator.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj
Validating the apprenticeship api type passed in for the creation of an
apprenticeship or creation of a commitment that contains apprenticeships.
=> Validate apprenticeship

src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj
to improve how errors are logged
=> enabled pdb for release build on web/api project

src/SFA.DAS.Commitments.Api.UnitTests/SFA.DAS.Commitments.Api.UnitTests.csproj, src/SFA.DAS.Commitments.Api.UnitTests/packages.config, src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj, src/SFA.DAS.Commitments.Api/packages.config, src/SFA.DAS.Commitments.Application.UnitTests/Queries/GetCommitment/WhenGettingCommitment.cs, src/SFA.DAS.Commitments.Application.UnitTests/Queries/GetEmployerCommitments/WhenGettingEmployerCommitments.cs, src/SFA.DAS.Commitments.Application.UnitTests/Queries/GetProviderCommitments/WhenGettingProviderCommitments.cs, src/SFA.DAS.Commitments.Application.UnitTests/Rules/CommitmentRules/WhenDetermineAgreementStatus.cs, src/SFA.DAS.Commitments.Application.UnitTests/SFA.DAS.Commitments.Application.UnitTests.csproj, src/SFA.DAS.Commitments.Application.UnitTests/packages.config, src/SFA.DAS.Commitments.Application/Queries/GetCommitment/GetCommitmentQueryHandler.cs, src/SFA.DAS.Commitments.Application/Queries/GetCommitments/GetCommitmentsQueryHandler.cs, src/SFA.DAS.Commitments.Application/Rules/CommitmentRules.cs, src/SFA.DAS.Commitments.Application/Rules/ICommitmentRules.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj, src/SFA.DAS.Commitments.Application/packages.config
- AgreementStatus, based on first apprenticeship
- ApprenticeshipCount
=> Setting status on commitment item

src/SFA.DAS.Commitments.Api/Controllers/EmployerController.cs, src/SFA.DAS.Commitments.Api/Controllers/ProviderController.cs, src/SFA.DAS.Commitments.Api/Orchestrators/EmployerOrchestrator.cs, src/SFA.DAS.Commitments.Api/Orchestrators/ProviderOrchestrator.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenCreatingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenValidatingCommand.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateCommitment/WhenCreatingCommitment.cs, src/SFA.DAS.Commitments.Application.UnitTests/Rules/ApprenticeshipUpdateRules/WhenDetermineNewAgreementStatus.cs, src/SFA.DAS.Commitments.Application/Commands/ApprenticeshipValidator.cs, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeship/CreateApprenticeshipCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/CreateCommitment/CreateCommitmentCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentAgreement/UpdateCommitmentAgreementCommand.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentAgreement/UpdateCommitmentAgreementCommandHandler.cs, src/SFA.DAS.Commitments.Application/Queries/GetCommitment/GetCommitmentQueryHandler.cs, src/SFA.DAS.Commitments.Application/Queries/GetCommitments/GetCommitmentsQueryHandler.cs, src/SFA.DAS.Commitments.Application/Rules/ApprenticeshipUpdateRules.cs, src/SFA.DAS.Commitments.Application/Rules/IApprenticeshipUpdateRules.cs, src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.refactorlog, src/SFA.DAS.Commitments.Database/Tables/Commitment.sql, src/SFA.DAS.Commitments.Database/Views/CommitmentSummary.sql, src/SFA.DAS.Commitments.Domain/Entities/Commitment.cs, src/SFA.DAS.Commitments.Domain/Entities/CommitmentSummary.cs, src/SFA.DAS.Commitments.Domain/Entities/LastAction.cs, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Infrastructure/Data/CommitmentRepository.cs
Updated the Domain types and the Queries to return the new LastAction column.
=> Add last action field

src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeship/WhenCreatingApprenticeship.cs, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeship/CreateApprenticeshipCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeship/UpdateApprenticeshipCommandHandler.cs
Preventing creation of apprenticeship where edit status or commitment status is invalid.
=> Check b4 creating apprenticeship

src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.sqlproj, src/SFA.DAS.Commitments.Database/StoredProcedures/SetPaymentOrder.sql, src/SFA.DAS.Commitments.Database/Tables/Apprenticeship.sql, src/SFA.DAS.Commitments.Domain/Data/ICommitmentRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Data/CommitmentRepository.cs
this is just the stored proc and data layer call to set payment order for all apprentices relating to an employer account. needs plumbng in incl. entity and event changes
=> added sproc to set payment order and dal call

src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateCommitmentAgreement/WhenUpdatingCommitmentAgreement.cs, src/SFA.DAS.Commitments.Application.UnitTests/Rules/ApprenticeshipUpdateRules/WhenDetermineWhetherChangeRequireAgreement.cs, src/SFA.DAS.Commitments.Application/Commands/SetPaymentOrder/SetPaymentOrderCommand.cs, src/SFA.DAS.Commitments.Application/Commands/SetPaymentOrder/SetPaymentOrderCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeship/UpdateApprenticeshipCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentAgreement/UpdateCommitmentAgreementCommandHandler.cs, src/SFA.DAS.Commitments.Application/Rules/ApprenticeshipUpdateRules.cs, src/SFA.DAS.Commitments.Application/Rules/CommitmentRules.cs, src/SFA.DAS.Commitments.Application/Rules/IApprenticeshipUpdateRules.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj, src/SFA.DAS.Commitments.Database/StoredProcedures/SetPaymentOrder.sql, src/SFA.DAS.Commitments.Domain/Entities/Apprenticeship.cs, src/SFA.DAS.Commitments.Domain/Interfaces/IApprenticeshipEvents.cs, src/SFA.DAS.Commitments.Infrastructure/Data/CommitmentRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Services/ApprenticeshipEvents.cs
when a cohort is approved, all apprentices belonging to the employer account have their payment order calculated. if any have changed then events are also published for each changed apprentice
=> Set payment order trigger

src/SFA.DAS.Commitments.Api/Controllers/EmployerController.cs, src/SFA.DAS.Commitments.Api/Controllers/ProviderController.cs, src/SFA.DAS.Commitments.Api/Orchestrators/EmployerOrchestrator.cs, src/SFA.DAS.Commitments.Api/Orchestrators/ProviderOrchestrator.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteApprenticeship/DeleteApprenticeshipCommand.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteApprenticeship/DeleteApprenticeshipCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteApprenticeship/DeleteApprenticeshipValidator.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteCommitment/DeleteCommitmentCommand.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteCommitment/DeleteCommitmentCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteCommitment/DeleteCommitmentValidator.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj, src/SFA.DAS.Commitments.Domain/Data/ICommitmentRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Data/CommitmentRepository.cs
NOTE: this is a "hard delete" only
=> hard delete apprenticeship (before agreed)

src/SFA.DAS.Commitments.Database/Views/ApprenticeshipSummary.sql
Please review and merge 3 x DCM-266 branches in EAS, Provider, and Commitments repositories together as they are inter-dependent
=> Makes NINO non-mandatory for approval

src/SFA.DAS.Commitments.Application.UnitTests/Rules/ApprenticeshipUpdateRules/WhenDetermineNewAgreementStatus.cs, src/SFA.DAS.Commitments.Application.UnitTests/Rules/ApprenticeshipUpdateRules/WhenDetermineNewEditStatus.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentAgreement/UpdateCommitmentAgreementCommandHandler.cs, src/SFA.DAS.Commitments.Application/Queries/GetCommitments/GetCommitmentsQueryHandler.cs, src/SFA.DAS.Commitments.Application/Rules/ApprenticeshipUpdateRules.cs, src/SFA.DAS.Commitments.Application/Rules/IApprenticeshipUpdateRules.cs, src/SFA.DAS.Commitments.Domain/Entities/CommitmentSummary.cs
TBC and merged along with Provider PR:
https://github.com/SkillsFundingAgency/das-providerapprenticeshipsservice/compare/DCM-269_Provider_New_Cohorts?expand=1
=> Changes how "New" cohort status is determined

src/SFA.DAS.Commitments.Infrastructure/Data/ApprenticeshipRepository.cs
*No merge until after release cut*
=> Fix where ULNs exceeding 50 characters can't be sent for overlap check

src/SFA.DAS.Commitments.Application/Queries/GetDataLocks/GetDataLocksQueryHandler.cs, src/SFA.DAS.Commitments.Database/Views/ApprenticeshipSummary.sql
Fixes mapping issue prevent resolution of subsequent datalocks
=> Fixes app summary view duplication on multiple datalocks

src/SFA.DAS.Commitments.Application.UnitTests/Queries/GetOverlappingApprenticeships/WhenGettingOverlappingApprenticeships.cs, src/SFA.DAS.Commitments.Application/Rules/ApprenticeshipOverlapRules.cs
=> Adds logic for using stopped date for stopped apprenticeship

src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/WhenGettingEmailTemplate.cs, src/SFA.DAS.Commitments.Notification.WebJob/EmailTemplatesService.cs
This is now released. Please Review & Merge this into Master.
=> Release_2017-06-14 into Master

src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeshipUpdate/WhenCreatingApprenticeshipUpdate.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeshipStatus/WhenStoppingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeshipUpdate/WhenUpdatingApprenticeshipUpdate.cs, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeshipUpdate/CreateApprenticeshipUpdateCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeshipStatus/UpdateApprenticeshipStatusCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeshipUpdate/UpdateApprenticeshipUpdateCommandHandler.cs
Changes for DCM-699
+ Correcting effective dates set on events for CoC
=> Data lock v1.1 change

src/SFA.DAS.Commitments.Application.UnitTests/Commands/CreateApprenticeshipUpdate/WhenCreatingApprenticeshipUpdate.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeshipStatus/UpdateApprenticeshipStatusBase.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeshipStatus/WhenStoppingApprenticeship.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeshipUpdate/WhenUpdatingApprenticeshipUpdate.cs, src/SFA.DAS.Commitments.Application/Commands/CreateApprenticeshipUpdate/CreateApprenticeshipUpdateCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeshipStatus/UpdateApprenticeshipStatusCommandHandler.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeshipUpdate/UpdateApprenticeshipUpdateCommandHandler.cs, src/SFA.DAS.Commitments.Database/StoredProcedures/GetDataLockStatusesByApprenticeshipId.sql, src/SFA.DAS.Commitments.Database/Views/ApprenticeshipSummary.sql, src/SFA.DAS.Commitments.Notification.WebJob/settings.job
This is now released into Prod. Please review and merge
=> Datalock v1.1 into Master

src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateApprenticeshipStatus/WhenPausingApprenticeship.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateApprenticeshipStatus/UpdateApprenticeshipStatusCommandHandler.cs
Pause now set EffectiveFrom date on event
=> Change event raised for Apprenticeship Pause

src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.sqlproj, src/SFA.DAS.Commitments.Database/StoredProcedures/GetProviderAlertsSummary.sql, src/SFA.DAS.Commitments.Domain/Data/IApprenticeshipRepository.cs, src/SFA.DAS.Commitments.Domain/Entities/ProviderAlertSummary.cs, src/SFA.DAS.Commitments.Domain/Entities/ProviderUser.cs, src/SFA.DAS.Commitments.Domain/Interfaces/IHttpClientWrapper.cs, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Infrastructure/Configuration/CommitmentsApiConfiguration.cs, src/SFA.DAS.Commitments.Infrastructure/Configuration/ProviderUserApiConfiguration.cs, src/SFA.DAS.Commitments.Infrastructure/Data/ApprenticeshipRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Data/IProviderEmailServiceWrapper.cs, src/SFA.DAS.Commitments.Infrastructure/Data/IdamsEmailServiceWrapper.cs, src/SFA.DAS.Commitments.Infrastructure/Models/UserResponse.cs, src/SFA.DAS.Commitments.Infrastructure/SFA.DAS.Commitments.Infrastructure.csproj, src/SFA.DAS.Commitments.Infrastructure/Services/HttpClientWrapper.cs, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/SFA.DAS.Commitments.Notification.WebJob.UnitTests.csproj, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/WhenGettingEmailTemplate.cs, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/WhenGettingProviderEmails.cs, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/WhenRunningNotificationJob.cs, src/SFA.DAS.Commitments.Notification.WebJob/Configuration/CommitmentNotificationConfiguration.cs, src/SFA.DAS.Commitments.Notification.WebJob/DependencyResolution/DefaultRegistry.cs, src/SFA.DAS.Commitments.Notification.WebJob/EmployerEmailTemplatesService.cs, src/SFA.DAS.Commitments.Notification.WebJob/INotificationJob.cs, src/SFA.DAS.Commitments.Notification.WebJob/IProviderEmailTemplatesService.cs, src/SFA.DAS.Commitments.Notification.WebJob/NotificationJob.cs, src/SFA.DAS.Commitments.Notification.WebJob/Program.cs, src/SFA.DAS.Commitments.Notification.WebJob/ProviderEmailTemplatesService.cs, src/SFA.DAS.Commitments.Notification.WebJob/SFA.DAS.Commitments.Notification.WebJob.csproj, src/SFA.DAS.Commitments.Notification.WebJob/Services/FakeProviderEmailServiceWrapper.cs
https://skillsfundingagency.atlassian.net/browse/DCM-654
👎
Config need some update (**SFA.DAS.CommitmentNotification_1.0**)
```json
"UseIdamsService": true,
"SendEmail": true,
"ProviderUserApi": {
"ProviderTestEmail": "",
"DasUserRoleId": "25806",
"IdamsListUsersUrl": "",
"ClientToken": ""
}
```
**SFA.DAS.Notifications-Templates_1.0**
```
{
"Id": "ProviderAlertSummaryNotification",
"EmailServiceId": "5fbc09cb-f958-4028-a967-e8e42d2e5c33"
}
```
👍
=> Dcm 654 provider notification

src/SFA.DAS.CommitmentPayments.WebJob.UnitTests/SFA.DAS.CommitmentPayments.WebJob.UnitTests.csproj, src/SFA.DAS.CommitmentPayments.WebJob.UnitTests/packages.config, src/SFA.DAS.CommitmentPayments.WebJob/SFA.DAS.CommitmentPayments.WebJob.csproj, src/SFA.DAS.CommitmentPayments.WebJob/packages.config, src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj, src/SFA.DAS.Commitments.Api/packages.config, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Domain/packages.config, src/SFA.DAS.Commitments.Infrastructure.UnitTests/SFA.DAS.Commitments.Infrastructure.UnitTests.csproj, src/SFA.DAS.Commitments.Infrastructure.UnitTests/packages.config, src/SFA.DAS.Commitments.Infrastructure/SFA.DAS.Commitments.Infrastructure.csproj, src/SFA.DAS.Commitments.Infrastructure/packages.config, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/SFA.DAS.Commitments.Notification.WebJob.UnitTests.csproj, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/packages.config, src/SFA.DAS.Commitments.Notification.WebJob/SFA.DAS.Commitments.Notification.WebJob.csproj, src/SFA.DAS.Commitments.Notification.WebJob/packages.config
Just an update to the logging packages
=> Updated Logging packages

src/SFA.DAS.Commitments.Database/Tables/Apprenticeship.sql, src/SFA.DAS.Commitments.Database/Tables/Message.sql
Included indices recommended by Azure prod DB
=> Add DB index recommendations

src/SFA.DAS.Commitments.Database/StoredProcedures/GetDataLockStatus.sql, src/SFA.DAS.Commitments.Database/StoredProcedures/GetDataLockStatusesByApprenticeshipId.sql, src/SFA.DAS.Commitments.Database/Views/ApprenticeshipSummary.sql
Yo.
Can you guys sanity check this change? It's to put the filter back in to filter out August data locks.
=> Added back in the August data lock filter.

src/SFA.DAS.Commitments.Infrastructure.UnitTests/Services/ApprenticeshipEventsTests/ApprenticeshipEventsTestsBase.cs, src/SFA.DAS.Commitments.Infrastructure/Services/ApprenticeshipEvents.cs
This is a quick fix. Need to move to using ApprenticeshipEventsPublisher
=> Added PriceHistory mapping for Obsolete event mapper

src/SFA.DAS.Commitments.Application.UnitTests/Commands/UpdateCommitmentAgreement/WhenUpdatingCommitmentAgreement.cs, src/SFA.DAS.Commitments.Application/Commands/UpdateCommitmentAgreement/UpdateCommitmentAgreementCommandValidator.cs
DCM-802 - Email Validation Issue
=> Update email regex to use same pattern as EmployerUsers

src/SFA.DAS.Commitments.Infrastructure/Data/IdamsEmailServiceWrapper.cs, src/SFA.DAS.Commitments.Notification.WebJob/EmployerEmailTemplatesService.cs, src/SFA.DAS.Commitments.Notification.WebJob/NotificationJob.cs, src/SFA.DAS.Commitments.Notification.WebJob/ProviderEmailTemplatesService.cs
Do you think we should log out the email addresses that we send to?
=> Update logging to be specific to Employer or Provider

src/SFA.DAS.CommitmentPayments.WebJob.UnitTests/SFA.DAS.CommitmentPayments.WebJob.UnitTests.csproj, src/SFA.DAS.CommitmentPayments.WebJob.UnitTests/packages.config, src/SFA.DAS.CommitmentPayments.WebJob/SFA.DAS.CommitmentPayments.WebJob.csproj, src/SFA.DAS.CommitmentPayments.WebJob/packages.config, src/SFA.DAS.Commitments.Api/App_Start/FilterConfig.cs, src/SFA.DAS.Commitments.Api/Global.asax.cs, src/SFA.DAS.Commitments.Api/Orchestrators/ValidationOrchestrator.cs, src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj, src/SFA.DAS.Commitments.Api/Web.config, src/SFA.DAS.Commitments.Api/packages.config, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Domain/packages.config, src/SFA.DAS.Commitments.Infrastructure.UnitTests/SFA.DAS.Commitments.Infrastructure.UnitTests.csproj, src/SFA.DAS.Commitments.Infrastructure.UnitTests/packages.config, src/SFA.DAS.Commitments.Infrastructure/SFA.DAS.Commitments.Infrastructure.csproj, src/SFA.DAS.Commitments.Infrastructure/packages.config, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/SFA.DAS.Commitments.Notification.WebJob.UnitTests.csproj, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/packages.config, src/SFA.DAS.Commitments.Notification.WebJob/SFA.DAS.Commitments.Notification.WebJob.csproj, src/SFA.DAS.Commitments.Notification.WebJob/packages.config
Can go with
https://github.com/SkillsFundingAgency/das-providerapprenticeshipsservice/pull/291
=> 647 logging correlation

src/SFA.DAS.Commitments.Domain/Entities/AcademicYear/AcademicYearValidationResult.cs, src/SFA.DAS.Commitments.Domain/Interfaces/IAcademicYearDateProvider.cs, src/SFA.DAS.Commitments.Domain/Interfaces/IAcademicYearValidator.cs, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Infrastructure.UnitTests/SFA.DAS.Commitments.Infrastructure.UnitTests.csproj, src/SFA.DAS.Commitments.Infrastructure.UnitTests/Services/AcademicYear/WhenDeterminingTheAcademicYear.cs, src/SFA.DAS.Commitments.Infrastructure.UnitTests/Services/AcademicYear/WhenValidatingAcademicYear.cs, src/SFA.DAS.Commitments.Infrastructure/SFA.DAS.Commitments.Infrastructure.csproj, src/SFA.DAS.Commitments.Infrastructure/Services/AcademicYearDateProvider.cs, src/SFA.DAS.Commitments.Infrastructure/Services/AcademicYearValidator.cs
=> Commitment academic year changes

src/SFA.DAS.CommitmentPayments.WebJob.UnitTests/SFA.DAS.CommitmentPayments.WebJob.UnitTests.csproj, src/SFA.DAS.CommitmentPayments.WebJob.UnitTests/packages.config, src/SFA.DAS.CommitmentPayments.WebJob/SFA.DAS.CommitmentPayments.WebJob.csproj, src/SFA.DAS.CommitmentPayments.WebJob/Updater/DataLockUpdater.cs, src/SFA.DAS.CommitmentPayments.WebJob/packages.config, src/SFA.DAS.Commitments.Api.UnitTests/SFA.DAS.Commitments.Api.UnitTests.csproj, src/SFA.DAS.Commitments.Api.UnitTests/packages.config, src/SFA.DAS.Commitments.Api/Orchestrators/Mappers/IDataLockMapper.cs, src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj, src/SFA.DAS.Commitments.Api/packages.config, src/SFA.DAS.Commitments.Database/StoredProcedures/GetDataLockStatusesByApprenticeshipId.sql, src/SFA.DAS.Commitments.Database/StoredProcedures/UpdateDataLockStatus.sql, src/SFA.DAS.Commitments.Database/Tables/DataLockStatus.sql, src/SFA.DAS.Commitments.Database/Views/ApprenticeshipSummary.sql, src/SFA.DAS.Commitments.Domain/Entities/DataLock/DataLockStatus.cs, src/SFA.DAS.Commitments.Domain/Entities/EventStatus.cs, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Infrastructure.UnitTests/SFA.DAS.Commitments.Infrastructure.UnitTests.csproj, src/SFA.DAS.Commitments.Infrastructure.UnitTests/Services/PaymentEventMapper/WhenMappingPaymentEvent.cs, src/SFA.DAS.Commitments.Infrastructure.UnitTests/packages.config, src/SFA.DAS.Commitments.Infrastructure/Data/ApprenticeshipUpdateRepository.cs, src/SFA.DAS.Commitments.Infrastructure/Data/DataLockRepository.cs, src/SFA.DAS.Commitments.Infrastructure/SFA.DAS.Commitments.Infrastructure.csproj, src/SFA.DAS.Commitments.Infrastructure/Services/PaymentEventMapper.cs, src/SFA.DAS.Commitments.Infrastructure/packages.config
https://skillsfundingagency.atlassian.net/browse/DCM-836
=> DCM-836 Provider Events API V2

src/SFA.DAS.Commitments.Infrastructure.UnitTests/Services/AcademicYear/WhenDeterminingTheAcademicYear.cs, src/SFA.DAS.Commitments.Infrastructure/Services/AcademicYearDateProvider.cs
=> Academic Year Changes

src/SFA.DAS.Commitments.AcademicYearEndProcessor.UnitTests/DatalockStatusTestData.cs, src/SFA.DAS.Commitments.AcademicYearEndProcessor.UnitTests/SFA.DAS.Commitments.AcademicYearEndProcessor.UnitTests.csproj, src/SFA.DAS.Commitments.AcademicYearEndProcessor.UnitTests/WhenRunningUpdate.cs, src/SFA.DAS.Commitments.AcademicYearEndProcessor.UnitTests/WhenTestingAcademicYearEndExpiryProcessor.cs, src/SFA.DAS.Commitments.AcademicYearEndProcessor.WebJob/Updater/AcademicYearEndExpiryProcessor.cs
Fixes premature expiry if web job is executed too soon after start of new academic year
=> DCM-751-Fix

src/SFA.DAS.Commitments.Api.Types/Apprenticeship/Apprenticeship.cs
Added PauseDate property to Apprenticeship
=> Update API Types for DCM-754

src/SFA.DAS.Commitments.Application.UnitTests/Commands/AcceptApprenticeshipChange/WhenAcceptingApprenticeshipChange.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/AcceptApprenticeshipChange/WhenMappingApprenticeshipUpdate.cs, src/SFA.DAS.Commitments.Application/Commands/AcceptApprenticeshipChange/AcceptApprenticeshipChangeMapper.cs, src/SFA.DAS.Commitments.Database/StoredProcedures/GetApprenticeshipWithPriceHistory.sql, src/SFA.DAS.Commitments.Database/StoredProcedures/GetApprenticeshipsWithPriceHistory.sql, src/SFA.DAS.Commitments.Infrastructure/Data/Transactions/ApprenticeshipTransactions.cs
https://skillsfundingagency.atlassian.net/browse/DCM-906
@satya-sanikommu do we want to merge this to your release branch and master?
/c
=> Dcm-906 price history from date

src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/WhenGettingEmailTemplate.cs, src/SFA.DAS.Commitments.Notification.WebJob.UnitTests/WhenGettingProviderEmails.cs, src/SFA.DAS.Commitments.Notification.WebJob/EmployerEmailTemplatesService.cs, src/SFA.DAS.Commitments.Notification.WebJob/ProviderEmailTemplatesService.cs
https://skillsfundingagency.atlassian.net/browse/DCM-881
Need to update templates with ((need_needs))
=> Update text for notification email.

src/SFA.DAS.Commitments.Events/ApprenticeshipUpdateAccepted.cs, src/SFA.DAS.Commitments.Events/ApprenticeshipUpdateCancelled.cs, src/SFA.DAS.Commitments.Events/ApprenticeshipUpdateCreated.cs, src/SFA.DAS.Commitments.Events/ApprenticeshipUpdateRejected.cs, src/SFA.DAS.Commitments.Events/CohortApprovalRequestedByProvider.cs, src/SFA.DAS.Commitments.Events/CohortApprovedByEmployer.cs
- We need to have messages with parameterless constructors to allow for the message processors to process them
=> Changed message to support message processing

src/SFA.DAS.Commitments.Database/StoredProcedures/GetProviderAlertsSummary.sql
Grabbing ProviderName from Commitments table for each providerId in NotificationSummary
=> Fix NotificationSummary getting duplicate providers

src/AzureTopicConfigurationStrucuture.json, src/SFA.DAS.Commitments.sln
- This is used to define azure topics for messages that are created in commitments. It also defines the subscriptions needed for each topic
=> Added Azure service bus template

src/SFA.DAS.Commitments.Api.Client/SFA.DAS.Commitments.Api.nuspec, src/SFA.DAS.Commitments.Api.Types/Apprenticeship/Apprenticeship.cs, src/SFA.DAS.Commitments.Api.Types/SFA.DAS.Commitments.Api.nuspec
First pull request (of 2) to add stopped date to view apprentice page.
This pull request basically just updates the x.Api.Types package with a change that is required in the next pull request.
=> DPP-1045_ShowCommitmentStopDate_pre1

src/SFA.DAS.Commitments.Application.UnitTests/Commands/DeleteCommitment/WhenDeletingCommitment.cs, src/SFA.DAS.Commitments.Application.UnitTests/Commands/DeleteCommitment/WhenValidatingCommand.cs, src/SFA.DAS.Commitments.Application/Commands/DeleteCommitment/DeleteCommitmentCommandHandler.cs
Publish a ProviderCohortApprovalUndoneByEmployerUpdate message if a provider approved cohort is deleted by an employer
=> DPP-1090_PublishEventWhenEmployerDeletesProviderApprovedCohort

src/SFA.DAS.Commitments.Api.Types/AgreementStatus.cs, src/SFA.DAS.Commitments.Api.Types/Commitment/CommitmentListItem.cs, src/SFA.DAS.Commitments.Api.Types/Commitment/Types/EditStatus.cs
Update api.types so we can generate a new nuget package for later work for this story.
Additive only so shouldn't break existing consumers.
=> DPP-1200_ViewCohortsFundedByTransfer_NonBreakingApiTypesPackageUpdates

src/SFA.DAS.Commitments.Api.UnitTests/Mapping/Service/Facets/WhenExtractingApprenticeshipStatuses.cs
Only unit test code has been changed!
=> fix date-run sensitive unit test

src/SFA.DAS.Commitments.Database/PostDeployment/PostDeploymentScript.sql
https://skillsfundingagency.atlassian.net/browse/DPP-1402
=> DPP-1402 Remove Apprenticeship Update Post-Deployment Script

src/SFA.DAS.Commitments.Api.Client.UnitTests/ApiClientTests/EmployerCommitmentApiTests.cs, src/SFA.DAS.Commitments.Api.Client/EmployerCommitmentApi.cs, src/SFA.DAS.Commitments.Api.Client/HttpCommitmentHelper.cs, src/SFA.DAS.Commitments.Api.Client/Interfaces/IEmployerCommitmentApi.cs, src/SFA.DAS.Commitments.Api.Client/Interfaces/IHttpCommitmentHelper.cs, src/SFA.DAS.Commitments.Api.Types/Apprenticeship/Apprenticeship.cs, src/SFA.DAS.Commitments.Api.UnitTests/Orchestrators/Employer/WhenGettingEmployerAccountIds.cs, src/SFA.DAS.Commitments.Api.UnitTests/Orchestrators/Mappers/WhenMappingAnApprenticeshipResult .cs, src/SFA.DAS.Commitments.Api.UnitTests/SFA.DAS.Commitments.Api.UnitTests.csproj, src/SFA.DAS.Commitments.Api/Controllers/EmployerController.cs, src/SFA.DAS.Commitments.Api/Orchestrators/EmployerOrchestrator.cs, src/SFA.DAS.Commitments.Api/Orchestrators/IEmployerOrchestrator.cs, src/SFA.DAS.Commitments.Api/Orchestrators/Mappers/ApprenticeshipMapper.cs, src/SFA.DAS.Commitments.Api/Orchestrators/Mappers/CommitmentMapper.cs, src/SFA.DAS.Commitments.Application.UnitTests/Queries/GetEmployerAccountIds/WhenGettingAllEmployerAccountIds.cs, src/SFA.DAS.Commitments.Application.UnitTests/SFA.DAS.Commitments.Application.UnitTests.csproj, src/SFA.DAS.Commitments.Application/Queries/GetEmployerAccountIds/GetEmployerAccountIdsQueryHandler.cs, src/SFA.DAS.Commitments.Application/Queries/GetEmployerAccountIds/GetEmployerAccountIdsRequest.cs, src/SFA.DAS.Commitments.Application/Queries/GetEmployerAccountIds/GetEmployerAccountIdsResponse.cs, src/SFA.DAS.Commitments.Application/SFA.DAS.Commitments.Application.csproj, src/SFA.DAS.Commitments.Database/StoredProcedures/GetActiveApprenticeshipsByULNs.sql, src/SFA.DAS.Commitments.Database/Views/ApprenticeshipSummary.sql, src/SFA.DAS.Commitments.Domain/Data/IApprenticeshipRepository.cs, src/SFA.DAS.Commitments.Domain/Entities/Apprenticeship.cs, src/SFA.DAS.Commitments.Domain/Entities/ApprenticeshipResult.cs, src/SFA.DAS.Commitments.Infrastructure/Data/ApprenticeshipRepository.cs
https://skillsfundingagency.atlassian.net/browse/DPP-1371
=> Dpp 1371 add new endpoint get accounts add transfersender field to all apprenticeships returned

src/SFA.DAS.Commitments.Database/AdhocScripts/Support/ApprenticeshipStopManyFixUpScript.sql, src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.sqlproj
Fixed errors from previous PR. New PR as I created a new branch to avoid unnecessary commits to unmodified file.
=> DPP-1703 stop commitments for provider

azure/template.json
Adding Infrastructure to support CommitmentsV2, To be deployed alongside current commitments. New Worker App Service plan and api Deployed to shared ASP.  New Storage account to allow the Deployment to be separated from main das-commitments deployment at later date.
=> Added ARM Template for Commitmentsv2 infrastructure

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client.UnitTests/SFA.DAS.CommitmentsV2.Api.Client.UnitTests.csproj, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/SFA.DAS.CommitmentsV2.Api.UnitTests.csproj, src/CommitmentsV2/SFA.DAS.CommitmentsV2/SFA.DAS.CommitmentsV2.csproj
=> Updates to latest api client and types library

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Program.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/SFA.DAS.CommitmentsV2.Api.csproj, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Startup.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Types/SFA.DAS.CommitmentsV2.Types.csproj
This adds swashbuckle (=== swagger + swagger.ui) to V2 das commitments. 
The docs are a bit bare bones currently.
=> Cv 270 swagger for api

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Responses/GetCohortResponse.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/CohortControllerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Controllers/CohortController.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryResponse.cs
This adds a flag to the get cohort summary query response to indicate whether the cohort is transfer funded..
=> CV-244 Add IsTransferFunded to GetCohortSummary

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client.TestHarness/Program.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client/CommitmentsApiClientFactory.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client/SFA.DAS.CommitmentsV2.Api.Client.csproj, src/SFA.DAS.Reservations.Api.Client/DependencyResolution/ReservationsApiClientRegistry.cs, src/SFA.DAS.Reservations.Api.Client/SFA.DAS.Reservations.Api.Client.csproj
The `SFA.DAS.Http.3.1.1` package now includes logging support.
=> CV-299 Updated SFA.DAS.Http package

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/AddCohortCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/AddCohortCommandWithOtherPartyHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/CohortDomainServiceTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortCommand.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortWithOtherPartyCommand.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortWithOtherPartyHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Domain/Interfaces/ICohortDomainService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/AccountLegalEntity.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/CohortDomainService.cs
Reverts SkillsFundingAgency/das-commitments#550
=> Revert "Cv 340 stop accountlegalentity getting created for wrong account"

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Requests/CreateCohortRequest.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Requests/CreateCohortWithOtherPartyRequest.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Responses/AccountLegalEntityResponse.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/AccountLegalEntityControllerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/IActionResultTestExtensions.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Controllers/AccountLegalEntityController.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/AddCohortCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/AddCohortCommandWithOtherPartyHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetAccountLegalEntity/GetAccountLegalEntityHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Mapping/RequestToCommandMappers/CreateCohortRequestToAddCohortCommandMapperTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Mapping/RequestToCommandMappers/CreateCohortWithOtherPartyRequestToAddCohortWithOtherPartyCommandMapperTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/CohortDomainServiceTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Validators/CreateCohortRequestValidatorTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Validators/CreateCohortWithOtherPartyRequestValidatorTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortCommand.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortWithOtherPartyCommand.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortWithOtherPartyHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/AddCohort/AddCohortWithOtherPartyValidator.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetAccountLegalEntity/GetAccountLegalEntityHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetAccountLegalEntity/GetAccountLegalEntityResponse.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Domain/Interfaces/ICohortDomainService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Mapping/RequestToCommandMappers/CreateCohortRequestToAddCohortCommandMapper.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Mapping/RequestToCommandMappers/CreateCohortWithOtherPartyRequestToAddCohortWithOtherPartyCommandMapper.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/AccountLegalEntity.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/CohortDomainService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Validators/CreateCohortRequestValidator.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Validators/CreateCohortWithOtherPartyRequestValidator.cs
Reverts SkillsFundingAgency/das-commitments#554
=> Revert "Revert "Cv 340 stop accountlegalentity getting created for wrong account""

src/SFA.DAS.Commitments.CloudService/Configuration/ServiceDefinition.Cloud.csdef, src/SFA.DAS.Commitments.CloudService/Configuration/ServiceDefinition.Release.csdef, src/SFA.DAS.Commitments.CloudService/ServiceConfiguration.Cloud.cscfg, src/SFA.DAS.Commitments.CloudService/ServiceConfiguration.Local.cscfg, src/SFA.DAS.Commitments.CloudService/ServiceConfiguration.MO.cscfg, src/SFA.DAS.Commitments.CloudService/ServiceConfiguration.PreProd.cscfg, src/SFA.DAS.Commitments.CloudService/ServiceConfiguration.Release.cscfg, src/SFA.DAS.Commitments.CloudService/ServiceDefinition.csdef
Removed Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString from cloud services' configuration files as it is unused.
=> Removed Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Responses/GetCohortResponse.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/CohortControllerTests/GetTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Controllers/CohortController.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers.TestHarness/TestHarness.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers.UnitTests/EventHandlerTestsFixture.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers.UnitTests/EventHandlers/CohortAssignedToProviderEventHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/DependencyResolution/IoC.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/EventHandlers/CohortAssignedToProviderEventHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/SFA.DAS.CommitmentsV2.MessageHandlers.csproj, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Messages/Events/CohortAssignedToProviderEvent.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryQueryResult.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Configuration/CommitmentsConfigurationKeys.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/SFA.DAS.CommitmentsV2.csproj, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Startup/IHostBuilderExtensions.cs, src/EmployerCohortApproved.txt, src/SFA.DAS.Commitments.Api/SFA.DAS.Commitments.Api.csproj, src/SFA.DAS.Commitments.sln
=> Adds IsApprovedByX properties to api response

src/SFA.DAS.Commitments.Api.UnitTests/Orchestrators/Mappers/WhenMappingApprenticeshipDataLockProperties.cs, src/SFA.DAS.Commitments.Api.UnitTests/SFA.DAS.Commitments.Api.UnitTests.csproj, src/SFA.DAS.Commitments.Api/Orchestrators/EmployerOrchestrator.cs, src/SFA.DAS.Commitments.Api/Orchestrators/Mappers/ApprenticeshipMapper.cs, src/SFA.DAS.Commitments.Api/Orchestrators/Mappers/IApprenticeshipMapper.cs, src/SFA.DAS.Commitments.Application/Queries/GetApprenticeships/GetApprenticeshipsQueryHandler.cs, src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.sqlproj, src/SFA.DAS.Commitments.Database/StoredProcedures/GetApprovedApprenticeshipsForEmployer.sql, src/SFA.DAS.Commitments.Database/StoredProcedures/GetApprovedApprenticeshipsForProvider.sql, src/SFA.DAS.Commitments.Domain/Data/IApprenticeshipRepository.cs, src/SFA.DAS.Commitments.Domain/Entities/Apprenticeship.cs, src/SFA.DAS.Commitments.Domain/Entities/DataLock/DataLockStatusSummary.cs, src/SFA.DAS.Commitments.Domain/Extensions/DataLockStatusSummaryExtensions.cs, src/SFA.DAS.Commitments.Domain/SFA.DAS.Commitments.Domain.csproj, src/SFA.DAS.Commitments.Infrastructure/Data/ApprenticeshipRepository.cs
Changes already raised in DPP-1593 https://github.com/SkillsFundingAgency/das-commitments/pull/412
=> New procs and model tweaks for search page

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/appsettings.Development.json, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/appsettings.json, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/DependencyResolution/DefaultRegistry.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/DependencyResolution/IoC.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/appsettings.Development.json, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/appsettings.json, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared/DependencyInjection/EmployerAccountsRegistry.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared/Services/StubAccountApiClient.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/ProcessFullyApprovedCohortCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/ProcessFullyApprovedCohort/ProcessFullyApprovedCohortCommandHandler.cs
Implements a stub accounts api client (v1)
=> Adds extra logging in key command handler

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared/ActionResults/FileCallbackResult.cs
Added FileCallbackResult which async loads the data from a stream and
produces a non blocking action.
=> MF-497 - Add FileCallbackResult

src/SFA.DAS.Commitments.Database/AdhocScripts/Manual/CV-656-Insert-AccountLegalEntities.sql, src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.sqlproj
Adhoc script to add AccountLegalEntities records for failed AddedLegalEntityEvent Events
=> CV-656 Insert AccountLegalEntites

src/SFA.DAS.Commitments.CloudService/ServiceConfiguration.Release.cscfg
Updated certificate thumbprint with valid certificate.
=> Updated Certificate Thumbprint

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Responses/GetApprenticeshipsResponse.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared.UnitTests/Services/CreateCsvServiceTests/WhenICreateACsvFile.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared/Services/CreateCsvService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Domain/Extensions/AlertsExtensionTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Domain/Extensions/ApprenticeshipStatusExtensionTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Extensions/PriceHistoryExtensions/WhenGettingTheLatestPrice.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Mapping/Apprenticeships/ApprenticeshipToApprenticeshipDetailsMapperTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/GetApprenticeshipsQueryResult.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/Search/Services/ApprenticeshipSearchService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/Search/Services/OrderedApprenticeshipSearchService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/Search/Services/ReverseOrderedApprenticeshipSearchService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Extensions/PriceHistoryExtensions.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Mapping/Apprenticeships/ApprenticeshipToApprenticeshipDetailsMapper.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Mapping/ResponseMappers/GetApprenticeshipsResponseMapper.cs
Also includes a change to the CSV download to include the comment about the age of the data being displayed.
=> MF-505 additional download fields

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/CohortDomainServiceTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/CohortDomainService.cs
and 'provider' when the employer is calling the validation
=> CV-764 Error message contains 'employer' when provider is calling validation

src/DefaultTargets.fsx
exclude building CommitmentsV2 projects in f# script
=> F sharp update

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client/CommitmentsApiClient.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Client/ICommitmentsApiClient.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Responses/GetAllProvidersResponse.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/ProviderControllerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Controllers/ProviderController.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetAllProviders/GetAllProvidersHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetAllProviders/GetAllProvidersQuery.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetAllProviders/GetAllProvidersQueryHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetAllProviders/GetAllProvidersQueryResult.cs
Adds a GetAllProviders method to the Commitments v2 api to populate the select list on the select new training provider page with the training providers name and ukprn
=> CON-2505 CoP new training provider

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/TrainingProgrammeControllerTests/WhenGettingATrainingProgramme.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Controllers/TrainingProgrammeController.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetTrainingProgramme/WhenGettingATrainingProgramme.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetTrainingProgramme/GetTrainingProgrammeQueryHandler.cs
When a course is not found then a 404 response should be returned by the controller, currently a bad request is being returned.
=> FAT2-414 - Ensure 404 response returned for course not found

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetApprenticeships/SearchTests/WhenGettingSortedApprenticeships.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/Search/Services/OrderedApprenticeshipSearchBaseService.cs
Corrected implementation of sorting to base it on payment status and by start date. Added new test case and repaired false positive test case for provider sort.
=> Ordered apprenticeship search by status

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetApprenticeships/SearchTests/WhenGettingSortedApprenticeships.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/Search/Services/OrderedApprenticeshipSearchBaseService.cs
Reverts SkillsFundingAgency/das-commitments#841
Not ready for merge yet
=> Revert "Ordered apprenticeship search by status"

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetApprenticeships/SearchTests/WhenGettingSortedApprenticeships.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetApprenticeships/Search/Services/OrderedApprenticeshipSearchBaseService.cs
Corrected implementation of sorting to base it on payment status and by start date. Added new test case and repaired false positive test case for provider sort.
=> CON-3462 Ordered apprenticeship search by status

src/SFA.DAS.Commitments.Database/PostDeployment/Patch_Apprenticeship_SV-1160.sql, src/SFA.DAS.Commitments.Database/PostDeployment/PostDeploymentScript.sql, src/SFA.DAS.Commitments.Database/SFA.DAS.Commitments.Database.sqlproj
Post-deployment script to patch historical Apprenticeship records to add Version.
=> SV-1160 Patch historical Apprenticeship records

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Models/Cohort/WhenApprovingCohort.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/DraftApprenticeship.cs
It allows a coe/cop to be done when there isn't a email
=> CS-1115-HotFIX added conditional approval status based on whether there is a continuationId

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.UnitTests/Controllers/AuthorizationControllerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/Controllers/AuthorizationController.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api/appsettings.Development.json, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers.UnitTests/CommandHandlers/ProviderApproveCohortCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/CommandHandlers/ProviderApproveCohortCommandHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/DependencyResolution/DefaultRegistry.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/CohortDomainServiceTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/EmailOptionalServiceTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetEmailOptional/GetEmailOptionalQuery.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetEmailOptional/GetEmailOptionalQueryHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Configuration/CommitmentsConfigurationKeys.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Configuration/EmailOptionalConfiguration.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/DependencyResolution/ConfigurationRegistry.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/DependencyResolution/DomainServiceRegistry.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Domain/Interfaces/IEmailOptionalService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/CohortDomainService.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/EmailOptionalService.cs
Cs 1035 email optional blacklist step3 employer
=> Cs 1035 email optional blacklist step3 employer

src/SFA.DAS.Commitments.Database/Functions/GetLearners.sql, src/SFA.DAS.Commitments.Database/Tables/Apprenticeship.sql
Add LastUpdated calculated field to Apprenticeship table to allow use in the Extract index.
=> SV-1259_Improve_PopulateLearner

src/SFA.DAS.Commitments.Database/Views/ApprenticeshipLatestCheck.sql
Same change to the ApprenticeshipLatestCheck as being applied to PopulateLearner in das-assessor-service
=> SV-1315_handle_duplicated_approvals

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Shared/Services/StubAccountApiClient.cs
=> PA-202 Update account stubs

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Types/DeliveryModel.cs
Hi Chris, as discussed to get this type in so we can NuGet reference the API for use with FJAA.
=> Add new type

src/CommitmentsV2/SFA.DAS.CommitmentsV2.Api.Types/Requests/BulkUploadAddDraftApprenticeshipsRequest.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/BulkUpload/BulkUploadValidateCommandHandlerTestsFixture.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/BulkUpload/ReservationValidationTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/RemoveAccountLegalEntityCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/ResendInvitationCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/ResumeApprenticeshipCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/StopApprenticeshipCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/UpdateApprenticeshipStopDateCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Mapping/Apprenticeships/EditValidation/ValidateApprenticeshipForEditRequestToValidateApprenticeshipForEditCommandTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Mapping/BulkUpload/BulkUploadDraftApprenticeshipRequestToDraftApprenticeshipDetailsMapperTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/SFA.DAS.CommitmentsV2.UnitTests.csproj, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/BulkUploadValidateRequest/BulkUploadValidateCommandHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/BulkUploadValidateRequest/ValidatePriorLearning.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Domain/Entities/DraftApprenticeshipDetails.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Mapping/BulkUpload/BulkUploadAddDraftApprenticeshipRequestToDraftApprenticeshipDetailsMapper.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/DraftApprenticeship.cs
The RPL fields are temporarily optional to allow communication of the file format change to software integrators.
=> PA-369 Bulk upload RPL

src/CommitmentsV2/SFA.DAS.CommitmentsV2/Validators/AddDraftApprenticeshipRequestValidator.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Validators/CreateCohortRequestValidator.cs
Hi Chris, sorry about that - another PR required as validators needed updating as part of enum type addition. Thanks
=> Validation necessary to be updated as part of new delivery model type

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Queries/GetCohortSummary/GetCohortSummaryQueryHandler.cs
…approve an apprentice learner record
=> FLP-84 Employer: Actual start date must have been entered to able to approve an apprentice learner record

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Models/Cohort/UpdatingDraftApprenticeship/WhenDraftApprenticeshipIsUpdated.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/DraftApprenticeship.cs
…t does not require further approval
=> FLP-91 Training provider: Adding ULN and opting learner into the pilot does not require further approval

azure-pipelines.yml
- Remove v1 API publish as this has been decomissioned
- Fix for v1 webjob deployment
=> V1 Webjob deployment fix

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/AcceptDataLockRequestChangesCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/ResolveDataLocks/AcceptDataLocksRequestChangesCommandHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/Apprenticeship.cs
Reverts SkillsFundingAgency/das-commitments#1198
This was accidentally merged. Since pulled out and does not require code review as had previously been done.
=> Revert "Pa 599 inc01405757 standardid updated bug"

src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/DataLockUpdaterService.cs
Re-opened for additional changes
=> Con 5060 data lock updater has had dl success exception

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/PriorLearningDataHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/CohortDomainServiceTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Application/Commands/PriorLearningData/RecognisePriorLearningDataHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Configuration/RplSettingsConfiguration.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/DraftApprenticeship.cs
Update to use rpl settings config
=> QT1-418_RPL_increase_total_reduction_limit

src/CommitmentsV2/SFA.DAS.CommitmentsV2/Data/ProviderCommitmentsDbContext.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Startup/EntityFrameworkStartup.cs
=> CON-5286 - SQL Connection Timeouts

azure-pipelines.yml, pipeline-templates/job/code-build.yml
Added steps/stage required to pack and push nuget packages
=> added pack and push nuget packages

src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Models/Cohort/AddDraftApprenticeshipValidationTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Models/Cohort/EditDraftApprenticeshipValidationTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Models/Cohort/UpdatingDraftApprenticeship/WhenDraftApprenticeshipIsUpdated.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Services/EditValidation/StartDateValidationTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Domain/Constants.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Extensions/DraftApprenticeshipExtensions.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Services/EditApprenticeshipValidationService.cs
- PS Pilot tests updated to use 01/11/2024 as new minimum start date
- New PS Pilot start date check in DraftApprenticeship
=> Port original change branch over to ps-release7.4

azure-pipelines.yml, azure/template.json, pipeline-templates/job/deploy.yml
Reverts SkillsFundingAgency/das-commitments#1403
=> Revert "Added failed requests alert and updated app connection string"

azure-pipelines.yml, azure/template.json, pipeline-templates/job/deploy.yml
Reverts SkillsFundingAgency/das-commitments#1407
=> Revert "DASD-12722 - Updated WebJob deployment task"

src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers.UnitTests/EventHandlers/ApprenticeshipWithdrawnEventHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.MessageHandlers/EventHandlers/ApprenticeshipWithdrawnEventHandler.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2.UnitTests/Application/Commands/StopApprenticeshipCommandHandlerTests.cs, src/CommitmentsV2/SFA.DAS.CommitmentsV2/Models/Apprenticeship.cs, src/SFA.DAS.Apprenticeships.Types/ApprenticeshipWithdrawnEvent.cs
=> FLP-1021 Added Stop Date update on full withdrawal
